#!/bin/bash

#Copyright 2018-present Open Networking Foundation
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.


rm -rf /opt/bcm68620
update-rc.d dev_mgmt_svc remove
update-rc.d openolt remove
update-rc.d hwmon_svc remove
update-rc.d htp_svc remove
rm -f /etc/init.d/dev_mgmt_svc
rm -f /etc/init.d/openolt
rm -f /etc/init.d/hwmon_svc
rm -f /etc/init.d/htp_svc

rm -rf /opt/openolt
#rm -rf /usr/local/lib/libgrpc.so
