#!/bin/bash

#Copyright 2018-present Open Networking Foundation
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.


rm -rf /opt/bcm68620
tar zxf /tmp/release_sda3016ss_custom_V2.0.0.1-20220425.tar.gz --strip-components=1 -C / 2>&1 > /dev/null
tar zxf /tmp/release_sda3016ss_V3.10.0.0-20220425.tar.gz --strip-components=1 -C / 2>&1 > /dev/null
rm -f /tmp/release_sda3016ss_custom_V2.0.0.1-20220425.tar.gz
rm -f /tmp/release_sda3016ss_V3.10.0.0-20220425.tar.gz
ln -sf /lib/platform-config/x86-64-zyxel-sda3016ss-r0/onl/lib/libonlp-x86-64-zyxel-sda3016ss.so /lib/platform-config/x86-64-zyxel-sda3016ss-r0/onl/lib/libonlp-x86-64-zyxel-sda3016ss.so.1
chmod +x /opt/bcm68620/sda3016ss/htp/htpNniLb
chmod +x /opt/bcm68620/sda3016ss/htp/htpPonLb
chmod +x /etc/init.d/dev_mgmt_svc
chmod +x /etc/init.d/openolt
chmod +x /etc/init.d/hwmon_svc
chmod +x /etc/init.d/htp_svc
update-rc.d dev_mgmt_svc defaults
update-rc.d openolt defaults
update-rc.d hwmon_svc defaults
update-rc.d htp_svc defaults
mkdir -p /tmp/bcmpon
echo "0:0,1:0" > /tmp/bcmpon/bcm68650_chip_reset

tar zxf /tmp/release_sda3016ss_openolt_V3.10.0.0-20220425.tar.gz -C / --strip-components=1
rm -f /tmp/release_sda3016ss_openolt_V3.10.0.0-20220425.tar.gz

